In [306]:
from ydata_profiling import ProfileReport
import pandas as pd

In [307]:
# -- READ DATABASES --

df_followup = pd.read_excel("db/Follow_Up_Dissertação.xlsx", skiprows=[0,1,2,3,4,5])

df_followup.columns

Index(['Código', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ' (AA=1 CA=2 CC=3) ', 'AA=1 CA+CC=2', 'CC=2 AA+CA=1', 'AA= 1 GA=2 GG=3',
       'AA=1 GA+GG=2', 'GG=2 AA+GA=1', 'CC=1 TC=2 TT=3', 'CC=1 TC+TT=2',
       'TC+CC=1 TT=2', 'TT=1 CT=2 CC=3', 'TT=1 CT+CC=2', 'CC=2 CT+TT=1',
       'GG=1 CG=2 CC=3', 'GG=1 CG+CC=2', 'CG+GG=1 CC=2', 'GG=1 CG=2 CC=3.1',
       'GG=1 CG+CC=2.1', 'CG+GG=1 CC=1', 'AA=1 GA=2 GG=3', 'AA=1 GA+GG-2',
       'GA+AA=1 GG=2', 'AA=1 GA=2 GG=3.1', 'AA=1 GA+GG=2.1', 'GA+AA=1 GG=2.1',
       'AA=1 GG=2', 'CC=1 CT=2 TT=3', 'CC=1 CT+TT=2', 'CT+CC=1 TT=2',
       'Hormonioterapia N=0 S=1', 'MEDICAMENTO3', 'Data inicial',
       'Radioterapia', 'Data inicial2', 'Data final3', 'MEDICAMENTO2',
       'Metástase óssea ', 'Orquei', 'Recidiva', 'CPRC', 'novo tumor', 'orgão',
       'óbito', 'data Obito', 'motivo do obito', 'Unnamed: 54'],
      dtype='object')

In [308]:
df_followup.head(5)

,Código,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Metástase óssea,Orquei,Recidiva,CPRC,novo tumor,orgão,óbito,data Obito,motivo do obito,Unnamed: 54
0,Pt 04,3,2,3,3,2,2,2,NaN,1,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1,Pt 09,2,2,1,3,2,2,2,NaN,1,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,Pt 10,2,2,1,2,2,1,3,NaN,2,...,1.0,1.0,1.0,1.0,2.0,NaN,1,2007-04-01,NaN,NaN
3,Pt 12,1,1,1,2,2,1,3,NaN,2,...,2.0,2.0,1.0,NaN,2.0,NaN,1,NaT,NaN,*Ultimo 2014
4,Pt 13,3,2,3,2,2,1,3,NaN,2,...,2.0,2.0,2.0,NaN,NaN,NaN,2,NaT,NaN,NaN

In [309]:
# -- FIX COLUMNS NAMES AND REMOVE UNWANTED COLUMNS --



df_followup = df_followup.rename(columns={"Código": "id",
                                          "Unnamed: 1": "GSTP1",
                                          "Unnamed: 4": "MGMT",
                                          "Unnamed: 7": "VDR",
                                          " (AA=1 CA=2 CC=3) ": "BCL2",
                                          "AA= 1 GA=2 GG=3": "CASP9",
                                          "CC=1 TC=2 TT=3": "NKX3",
                                          "TT=1 CT=2 CC=3": "CASP3",
                                          "GG=1 CG=2 CC=3": "PTEN",
                                          "GG=1 CG=2 CC=3.1": "AKT1",
                                          "AA=1 GA=2 GG=3": "PI3K",
                                          "AA=1 GA=2 GG=3.1": "AMACR",
                                          "AA=1 GG=2": "AR",
                                          "CC=1 CT=2 TT=3": "MTOR",
                                          "Recidiva": "cancer_recurrence"})

df_followup = df_followup.drop(df_followup.columns[[2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 27, 29, 30, 32, 33, 36, 37]], axis=1)

df_followup.columns

Index(['id', 'GSTP1', 'MGMT', 'VDR', 'BCL2', 'CASP9', 'NKX3', 'CASP3', 'PTEN',
       'AKT1', 'PI3K', 'AMACR', 'AR', 'MTOR', 'Hormonioterapia N=0 S=1',
       'MEDICAMENTO3', 'Data inicial', 'Radioterapia', 'Data inicial2',
       'Data final3', 'MEDICAMENTO2', 'Metástase óssea ', 'Orquei',
       'cancer_recurrence', 'CPRC', 'novo tumor', 'orgão', 'óbito',
       'data Obito', 'motivo do obito', 'Unnamed: 54'],
      dtype='object')

In [310]:
# -- REPLACE INT VALUES TO STR --

gstp1_dict = {1: "GG", 2: "AG", 3: "AA"}
mgmt_dict = {1: "GG", 2: "AG", 3: "AA"}
vdr_dict = {1: "TT", 2: "TC", 3: "CC"}
bcl2_dict = {1: "AA", 2: "CA", 3: "CC"}
casp9_dict = {1: "AA", 2: "GA", 3: "GG"}
nkx3_dict = {1: "CC", 2: "TC", 3: "TT"}
casp3_dict = {1: "TT", 2: "CT", 3: "CC"}
pten_dict = {1: "GG", 2: "CG", 3: "CC"}
akt1_dict = {1: "GG", 2: "CG", 3: "CC"}
pi3k_dict = {1: "AA", 2: "GA", 3: "GG"}
amacr_dict = {1: "AA", 2: "GA", 3: "GG"}
ar_dict = {1: "AA", 2: "GG"}
mtor_dict = {1: "CC", 2: "CT", 3:"TT"}

gene_dict = {
    "GSTP1": gstp1_dict,
    "MGMT" : mgmt_dict,
    "VDR" : vdr_dict,
    "BCL2": bcl2_dict,
    "CASP9" : casp9_dict,
    "NKX3" : nkx3_dict,
    "CASP3" : casp3_dict,
    "PTEN" : pten_dict,
    "AKT1" : akt1_dict,
    "PI3K" : pi3k_dict,
    "AMACR" : amacr_dict,
    "AR" : ar_dict,
    "MTOR" : mtor_dict
}

for key, value in gene_dict.items():
    if key in df_followup.columns:
        df_followup[key] = df_followup[key].replace(value)

df_followup.head(5)

,id,GSTP1,MGMT,VDR,BCL2,CASP9,NKX3,CASP3,PTEN,AKT1,...,Metástase óssea,Orquei,cancer_recurrence,CPRC,novo tumor,orgão,óbito,data Obito,motivo do obito,Unnamed: 54
0,Pt 04,AA,AA,TC,CC,GA,TC,CC,CG,CG,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1,Pt 09,AG,AA,TC,CA,GA,TC,TT,CG,CC,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,Pt 10,AG,AG,CC,CA,GA,TC,CC,GG,CC,...,1.0,1.0,1.0,1.0,2.0,NaN,1,2007-04-01,NaN,NaN
3,Pt 12,GG,AG,CC,CA,GG,TC,CC,CG,CC,...,2.0,2.0,1.0,NaN,2.0,NaN,1,NaT,NaN,*Ultimo 2014
4,Pt 13,AA,AG,CC,CA,GA,TT,CC,CG,CC,...,2.0,2.0,2.0,NaN,NaN,NaN,2,NaT,NaN,NaN

In [311]:
# REMOVE UNWANTED COLLUMNS

display(df_followup.iloc[:, 14:].head())

df_followup.iloc[:, 23].value_counts()

df_followup = df_followup.drop(df_followup.iloc[:, 14:23], axis=1)
df_followup = df_followup.drop(df_followup.iloc[:, 15:], axis=1)

df_followup.head(5)

,Hormonioterapia N=0 S=1,MEDICAMENTO3,Data inicial,Radioterapia,Data inicial2,Data final3,MEDICAMENTO2,Metástase óssea,Orquei,cancer_recurrence,CPRC,novo tumor,orgão,óbito,data Obito,motivo do obito,Unnamed: 54
0,2,NaN,NaT,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1,2,NaN,NaT,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,2,NaN,NaT,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,NaN,1,2007-04-01,NaN,NaN
3,2,NaN,NaT,1.0,2011-07-01 00:00:00,2011-09-01 00:00:00,NaN,2.0,2.0,1.0,NaN,2.0,NaN,1,NaT,NaN,*Ultimo 2014
4,2,NaN,NaT,2.0,NaN,NaN,N,2.0,2.0,2.0,NaN,NaN,NaN,2,NaT,NaN,NaN

,id,GSTP1,MGMT,VDR,BCL2,CASP9,NKX3,CASP3,PTEN,AKT1,PI3K,AMACR,AR,MTOR,cancer_recurrence
0,Pt 04,AA,AA,TC,CC,GA,TC,CC,CG,CG,GA,GG,GG,CT,2.0
1,Pt 09,AG,AA,TC,CA,GA,TC,TT,CG,CC,GG,GA,AA,CT,2.0
2,Pt 10,AG,AG,CC,CA,GA,TC,CC,GG,CC,GA,GG,GG,CC,1.0
3,Pt 12,GG,AG,CC,CA,GG,TC,CC,CG,CC,GA,AA,AA,CT,1.0
4,Pt 13,AA,AG,CC,CA,GA,TT,CC,CG,CC,GG,GA,AA,CT,2.0

In [312]:
# -- FIX COLUMNS NAMES AND VALUES --

df_followup["id"] = df_followup["id"].apply(lambda x: x.replace(" ", "").upper())
df_followup["cancer_recurrence"] = df_followup["cancer_recurrence"].replace({2: 0})

df_followup.head(5)

,id,GSTP1,MGMT,VDR,BCL2,CASP9,NKX3,CASP3,PTEN,AKT1,PI3K,AMACR,AR,MTOR,cancer_recurrence
0,PT04,AA,AA,TC,CC,GA,TC,CC,CG,CG,GA,GG,GG,CT,0.0
1,PT09,AG,AA,TC,CA,GA,TC,TT,CG,CC,GG,GA,AA,CT,0.0
2,PT10,AG,AG,CC,CA,GA,TC,CC,GG,CC,GA,GG,GG,CC,1.0
3,PT12,GG,AG,CC,CA,GG,TC,CC,CG,CC,GA,AA,AA,CT,1.0
4,PT13,AA,AG,CC,CA,GA,TT,CC,CG,CC,GG,GA,AA,CT,0.0

In [313]:
display(df_followup["cancer_recurrence"].value_counts(dropna=False))

# -- MISSING VALUES IN TARGET --

# Only 2 rows, decided to drop
df_followup = df_followup.dropna()

df_followup["cancer_recurrence"].value_counts(dropna=False)

cancer_recurrence
0.0    110
1.0    109
NaN      2
Name: count, dtype: int64

cancer_recurrence
0.0    110
1.0    109
Name: count, dtype: int64

In [314]:
# -- RUN YDATA PROFILING --

#profile = ProfileReport(df_followup, title="Recurrence Data Report")
#profile.to_file("data_report.html")

In [315]:
# -- GET CATEGORIES FOR GENES --

df_followup = pd.get_dummies(df_followup, columns=gene_dict.keys(), dtype=int)
df_followup["cancer_recurrence"] = df_followup["cancer_recurrence"].astype(int)

display(df_followup.head(5))
print(df_followup.shape)

,id,cancer_recurrence,GSTP1_AA,GSTP1_AG,GSTP1_GG,MGMT_AA,MGMT_AG,MGMT_GG,VDR_CC,VDR_TC,...,PI3K_GA,PI3K_GG,AMACR_AA,AMACR_GA,AMACR_GG,AR_AA,AR_GG,MTOR_CC,MTOR_CT,MTOR_TT
0,PT04,0,1,0,0,1,0,0,0,1,...,1,0,0,0,1,0,1,0,1,0
1,PT09,0,0,1,0,1,0,0,0,1,...,0,1,0,1,0,1,0,0,1,0
2,PT10,1,0,1,0,0,1,0,1,0,...,1,0,0,0,1,0,1,1,0,0
3,PT12,1,0,0,1,0,1,0,1,0,...,1,0,1,0,0,1,0,0,1,0
4,PT13,0,1,0,0,0,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0

(219, 39)